#!/bin/sh

cd /home/argershm/180-voltmeter/Analog/cc
run_times=0
until [ $run_times -gt 1 ]
do
    ((run_times++))
    if [ $run_times -gt 1 ]
    then
        export SNPS_PW_SIM_SERVER_RERUN=1
        script_pgid=`ps -o pgid= $$ | grep -o '[0-9]*'`
        pid_with_same_pgid=`ps -eo pid,pgid | awk '$2 == "'$script_pgid'" { print $1 }'`
        echo $pid_with_same_pgid | grep -v $$ | xargs kill -9
    fi
    primewave -gui 0 -uniqueString 424077b79e1069ee007c9cb2fe8bc338d6c7980de498070fc2511cd128a4b2dec1cb7792ad94754281a40689e99ba2662680066a2596610a -python 0 -command "source /home/argershm/180-voltmeter/Analog/cc/synopsys_custom/sim_server/custom_compiler.argershm/stb.gmid.gmid_nfet_3v3.schematic.session4/sim_server_init.tcl" -log /home/argershm/180-voltmeter/Analog/cc/synopsys_custom/primewave_session4_sim_server_job2 -libDefFile /home/argershm/180-voltmeter/Analog/cc/lib.defs && break
done
