#!/bin/sh

#Created by PW DP.

WDIR=`dirname $0`
cd $WDIR

if [ "x$CDPL_LOGDIR" = "x" ] ; then
export CDPL_LOGDIR=$WDIR/logs
fi

export SYNOPSYS_USE_PW_WORKER_CI=1
mkdir -p $WDIR/logs/w$CDPL_WORKERID

export HOME=/home/argershm

export PATH=/mnt/apps/public/COE/synopsys_apps/customcompiler/W-2024.09-SP1-2/bin:/mnt/apps/public/COE/synopsys_apps/customcompiler/W-2024.09-SP1-2/linux64/bin:/mnt/apps/public/COE/synopsys_apps/customcompiler/W-2024.09-SP1-2/linux64/OA/bin:/mnt/apps/public/COE/synopsys_apps/customcompiler/W-2024.09-SP1-2/linux64/PyCellStudio/linux64/3rd/bin:/mnt/apps/public/COE/synopsys_apps/customcompiler/W-2024.09-SP1-2/linux64/PyCellStudio/bin:/home/argershm/.local/bin:/home/argershm/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/cuda/bin:/opt/puppetlabs/bin:/usr/lib/fastx/3/apps:/mnt/apps/public/COE/synopsys_apps/syn/W-2024.09-SP2/bin:/mnt/apps/public/COE/synopsys_apps/primesim/W-2024.09-SP1-2/bin:/mnt/apps/public/COE/synopsys_apps/icvalidator/W-2024.09-SP2/bin/linux64:/mnt/apps/public/COE/synopsys_apps/customcompiler/W-2024.09-SP1-2/bin:/mnt/apps/public/COE/synopsys_apps/primewave/W-2024.09-SP1-2/bin:/bin

export SYNOPSYS_DYNAMIC_DISTRIBUTION_CHECK_TMP_ERROR=1
export SYNOPSYS_DYNAMIC_DISTRIBUTION_USE_NW_PHASE_II_WORKER=1
export SYNOPSYS_DYNAMIC_DISTRIBUTION_CC_CUSTOM_LOCAL=/home/argershm/180-voltmeter/Analog/cc/synopsys_custom

host=`hostname`
wk_out=$WDIR/logs/worker.W$CDPL_WORKERID.$host.$$.out
wk_start_time=`date -u`
if [ ! -e "$wk_out" ]; then
echo "[$wk_start_time]Running $@" > $wk_out 2>&1
    if [ $# -eq 5 ]; then
        export SYNOPSYS_DYNAMIC_DISTRIBUTION_PW_WORKER_CI_ARGS=$3:$5
    fi

    if [ $# -eq 7 ]; then
        export SYNOPSYS_DYNAMIC_DISTRIBUTION_PW_WORKER_CI_ARGS=$3:$5:$7
    fi

cd /home/argershm/180-voltmeter/Analog/cc;$1_ci -gui 0 -localDir $WDIR/logs/w$CDPL_WORKERID >> $wk_out 2>&1
else
echo "[$wk_start_time]Running $@" >> $wk_out 2>&1
    if [ $# -eq 5 ]; then
        export SYNOPSYS_DYNAMIC_DISTRIBUTION_PW_WORKER_CI_ARGS=$3:$5
    fi

    if [ $# -eq 7 ]; then
        export SYNOPSYS_DYNAMIC_DISTRIBUTION_PW_WORKER_CI_ARGS=$3:$5:$7
    fi

cd /home/argershm/180-voltmeter/Analog/cc;$1_ci -gui 0 -localDir $WDIR/logs/w$CDPL_WORKERID >> $wk_out 2>&1
fi